### ISSUE TITLE
[Question] Where is the environment chase-circle ?

### ISSUE THREAD

**Issue by gasse** [Farama-Foundation/miniwob-plusplus#82]
### Question

I see there is an HTML environment called `chase-circle`
https://github.com/Farama-Foundation/miniwob-plusplus/blob/master/miniwob/html/miniwob/chase-circle.html

However this environment is absent from the python codebase
https://github.com/Farama-Foundation/miniwob-plusplus/blob/master/miniwob/envs/miniwob_envs.py

Is there a reason for that? Has it been forgotten somehow? Or is it not ready yet to be part of the benchmark?

**Comment by ppasupat** [comment]
As explained in the [documentation](https://miniwob.farama.org/environments/list/#excluded-tasks), `chase-circle` is one of the excluded tasks. These are time-dependent tasks that require the agent to wait for events to happen before acting. Since the Selenium environment does not have a fixed frame rate, the agent might not get to see some of those events, so we think it's less consistent to benchmark on such tasks.

**Comment by gasse** [comment]
@ppasupat that makes sense. Thank you for the quick reply!
